### ISSUE TITLE
columns backend refactor

### ISSUE THREAD

**Issue by vzaragoza** [juaismar/gormssp#52]
The map[int]SSP.Data can be an array (**[]SPP.Data**) so you can have empty columns.

Current code stops if a column is empty: 
```
column[0] = ...
column[2] ...
```
It will stop checking column[1] since it is **nil**, so column[2] will not have any value.

If it was an array you could run over all values and ignore only **nil** values.

**Comment by juaismar** [comment]
Done in #54
